const fs = require('fs');
const path = require('path');
const { GoogleGenerativeAI } = require("@google/generative-ai");
require('dotenv').config({ path: path.resolve(__dirname, '../.env.local') });

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

const languages = {
  hi: "Hindi",
  bn: "Bengali",
  te: "Telugu",
  mr: "Marathi",
  ta: "Tamil",
  gu: "Gujarati",
  kn: "Kannada",
  ml: "Malayalam",
  or: "Odia",
  pa: "Punjabi",
  ur: "Urdu"
};

async function translateAll() {
  console.log("🚀 Starting AI Translation Engine...");

  const sourcePath = path.join(__dirname, 'source.json');
  const source = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));
  
  let finalTranslations = { en: source };

  for (const [code, name] of Object.entries(languages)) {
    console.log(`⏳ Translating to ${name} (${code})...`);
    
    const prompt = `
      Translate the following JSON object values into ${name}.
      Keep the keys exactly the same.
      Return ONLY the JSON string, no markdown, no quotes outside.
      
      JSON:
      ${JSON.stringify(source)}
    `;

    try {
      const result = await model.generateContent(prompt);
      const response = result.response;
      let text = response.text();

      text = text.replace(/```json/g, '').replace(/```/g, '').trim();
      
      finalTranslations[code] = JSON.parse(text);
      console.log(`✅ ${name} done.`);
    } catch (error) {
      console.error(`❌ Failed ${name}:`, error.message);
      finalTranslations[code] = source; 
    }
  }

  const fileContent = `
// THIS FILE IS AUTO-GENERATED BY AI. DO NOT EDIT MANUALLY.
// Run: node scripts/translate.js

import { Language } from "@/store/useLanguageStore";

export const translations: Record<Language, any> = ${JSON.stringify(finalTranslations, null, 2)};
  `;

  const outputPath = path.join(__dirname, '../src/lib/translations.ts');
  fs.writeFileSync(outputPath, fileContent);

  console.log("\n✨ Success! 'src/lib/translations.ts' has been updated with all languages.");
}

translateAll();